### ISSUE TITLE
Missing indexer documentation and/or functionality

### ISSUE THREAD

**Issue by n4zmz** [devopsarr/terraform-provider-prowlarr#147]
The provider does not have anything documented for the indexers which is the key to Prowlarr.

**Comment by Fuochi** [comment]
Hi @n4zmz,
Yes, the indexer resource and data sources are still missing. I'll add them in the next release, I'll try to do that by the end of the month.
However, just to give you a heads-up, the resource will be a bit different than the one I created for other providers, since I cannot create a separate resource for each and every indexer.
I am still thinking about its exact implementation.

**Comment by JefeDavis** [comment]
@Fuochi look like the work is done, anytime line on when this will get merged? #149

**Comment by Fuochi** [comment]
Hi @JefeDavis, I'm planning on merge that by the end of the week. Just wanted to squeeze in a notification improvement

**Comment by Fuochi** [comment]
Feature integrated in v2.0.0 (#149)  As mentioned the way of leveraging fields is different from other resources.
Companion data sources for indexer schema have been provided to ease the adoption.
