### ISSUE TITLE
Unexpected attribute: authorization

### ISSUE THREAD

**Issue by chkpwd** [devopsarr/terraform-provider-prowlarr#201]
```hcl
terraform {
  required_providers {
    prowlarr = {
      source = "devopsarr/prowlarr"
      version = "2.2.0"
    }
  }
}
```

The provider has been updated. Yet the attribute cannot be used.

![image](https://github.com/devopsarr/terraform-provider-prowlarr/assets/132493975/6c7b0a5b-39bf-4eca-9a06-a095d2fe38e7)
![image](https://github.com/devopsarr/terraform-provider-prowlarr/assets/132493975/c7a1092a-4df7-4572-8907-a682c8d74b6a)

**Comment by Fuochi** [comment]
Hi @chkpwd,
I think that's just a cosmetic error of your IDE. I tried to init and plan, and it works. However I have some bad news. The apply didn't work:
<img width="525" alt="Screenshot 2024-02-03 at 08 43 32" src="https://github.com/devopsarr/terraform-provider-prowlarr/assets/4720478/7c996284-359c-4112-a248-ab40c5e7de3a">
And that's because the APIs don't accept basic auth as an authentication method:
```bash
curl http://127.0.0.1:9696/api/v1/tag -v -H "Authorization: Basic dGVzdDp0ZXN0MTIzNA=="  
*   Trying 127.0.0.1:9696...
* Connected to 127.0.0.1 (127.0.0.1) port 9696
> GET /api/v1/tag HTTP/1.1
> Host: 127.0.0.1:9696
> User-Agent: curl/8.4.0
> Accept: */*
> Authorization: Basic dGVzdDp0ZXN0MTIzNA==
> 
< HTTP/1.1 401 Unauthorized
< Content-Length: 0
< Date: Sat, 03 Feb 2024 07:48:56 GMT
< Server: Kestrel
< 
* Connection #0 to host 127.0.0.1 left intact
```
It was actually written here:
https://github.com/Prowlarr/Prowlarr/blob/1bb1ec6106caddfa0b1f4c1b5f38fef11c649286/src/Prowlarr.Api.V1/openapi.json#L6376-L6390
We should've checked before.

**Comment by chkpwd** [comment]
This adds support querying the api when prowlarr is behind a SSO (authentik, authelia). 

```bash
❯ curl \
'https://prowlarr.k8s.chkpwd.com/api/v1/history' \
-H 'accept: application/json' \
-H 'X-Api-Key: 9a3f8d25dd4a3ec4bd69f6e05ff83c3f' \
-H 'Authorization: Basic base64_encoded_creds'
{
  "page": 1,
  "pageSize": 10,
  "sortKey": "date",
  "sortDirection": "descending",
  "totalRecords": 5673,
  "records": [
    {
      "indexerId": 39,
      "date": "2024-02-05T00:33:11Z",
      "successful": true,
      "eventType": "indexerRss",
      "data": {
        "limit": "100",
        "offset": "0",
        (...) # Removed for brevity
```

**Comment by chkpwd** [comment]
#202 created to fix this.

**Comment by Fuochi** [comment]
Ok, I didn't get this on #196. I thought you wanted to use Prowlarr's basic authentication (which I now understand it doesn't work).
Then why don't you use unauthenticated paths? [authentik ref](https://goauthentik.io/docs/providers/proxy/#allowing-unauthenticated-requests).
This way you'll avoid having double authentication for the api paths. They suggest the same approach in [Prowlarr's doc](https://wiki.servarr.com/en/prowlarr/installation/reverse-proxy)

**Comment by Fuochi** [comment]
Hi @chkpwd,
I have implemented this: https://github.com/devopsarr/terraform-provider-sonarr/commit/c8c452283318c63583845f08f45edfb7327f4fb6 in Sonarr's provider that should allow users to add custom headers. Will that be ok for you to to use the Authorization header instead of `prowlarr_authorization`. If yes, I'll try to add this feature in march

**Comment by chkpwd** [comment]
I apologize for the lack of response. Been working on some other projects. Your changes look good. LGTM 👍🏾

**Comment by Fuochi** [comment]
Hi @chkpwd,
with a huge delay, I finally released this change in v2.4.0, I also removed authorization since it wasn't doing what we expected. Feel free to try it out, if you are still using the provider!

**Comment by Fuochi** [comment]
@chkpwd we can close this, right?

**Comment by chkpwd** [comment]
Yea. Sorry.
